### PR TITLE
PHP 8 Support

### PR DESCRIPTION
**Pull request by adithyasrinivasan**
Hi,

https://github.com/elastic/elasticsearch-php has just released the new package for PHP8 support. I've updated the dependencies and fixed a couple things.

Thanks!

### CODE REVIEW

**Review by Sekaiichi — APPROVED** [review]

**Comment by adithyasrinivasan** [comment]
Hi, any luck on this please?

**Review by sudhanshukrdev — APPROVED** [review]

**Review by eqxDev — APPROVED** [review]

**Comment by aaronhuisinga** [comment]
We've done plenty of testing with this PR on our staging environment, and this seems to be working properly. Would love to see this merged!

**Review by aaronhuisinga — APPROVED** [review]

**Comment by ardziej** [comment]
@babenkoivan can you merge it?

**Review by ardziej — APPROVED** [review]

**Review by ardziej — APPROVED** [review]
Works ok. Let's merge it.

**Comment by babenkoivan** [comment]
Thank you all for the PR and testing 🙂

**Pull request merged**
