### PR TITLE
Fix delete to use refresh option

### PR DESCRIPTION
**Pull request by mtvs**

### CODE REVIEW

**Comment by iget-esoares** [comment]
@mtvs Can you explain this PR?

**Comment by mtvs** [comment]
Here, I've added the missing check for `document_refresh` option within `delete()` in the indexer classes to set the `refresh` option for the elastic client accordingly.

**Comment by iget-esoares** [comment]
Makes sense to me. I'm merging it.

**Comment by iget-esoares** [comment]
Released in v4.0.5

**Pull request merged**
