### PR TITLE
Switch to Laravel preset for StyleCI

### PR DESCRIPTION
**Pull request by lucasmichot**
Switch to Laravel preset for StyleCI

### CODE REVIEW

**Comment by iget-esoares** [comment]
Could you please explain the reason and differences between these presets?

**Comment by lucasmichot** [comment]
> Could you please explain the reason and differences between these presets?

This repository is a Laravel package, thus It feels following the same presets make sense and would help next PR style consistency.

All rules applied by this preset can be found here: https://docs.styleci.io/presets#laravel

**Comment by iget-esoares** [comment]
Makes sense for me. I'll aprove it

**Comment by iget-esoares** [comment]
Merged to master. Next PR's must follow this preset

**Pull request merged**
