### PR TITLE
Enforce Laravel param spacing.

### PR DESCRIPTION
**Pull request by lucasmichot**
Enforce Laravel param spacing.

### CODE REVIEW

**Comment by iget-esoares** [comment]
I like this spacing, but do the StyleCI enforces it? Or new changes will need this check manually?

**Comment by lucasmichot** [comment]
> Or new changes will need this check manually?

Next changes will automatically be fixed by StyleCI.
Anytime docblocks are added or updated.

**Comment by lucasmichot** [comment]
Can this be reviewed @iget-esoares ?

**Comment by iget-esoares** [comment]
@lucasmichot Thanks for your contribution. I'm merging this.

**Pull request merged**
