### PR TITLE
Elasticsearch with aggregations, suggesters, macro function, custom script sorting & paginate with lazy loading

### PR DESCRIPTION
**Pull request by rankarpan**
+ Aggregations
+ Suggesters
+ Macro Function Like Count, Hydrate etc...
+ Custom Script Sorting
+ Paginate With Lazy Loading

### CODE REVIEW

**Comment by ametad** [comment]
Looks great!

**Comment by ametad** [comment]
@babenkoivan will you consider pull this in? How do you look to this?

These are a lot of functionalities that we would like to use.

Kind regards!

**Comment by NexPB** [comment]
Ye, I would love to use this aswell.

**Comment by babenkoivan** [comment]
Hi @rankarpan, you did a really tremendous job here! 
But unfortunately, I have to disappoint you - I won't merge it. 

I'll try to explain myself. I wasn't sure whether to merge it or not for a long time, because you implemented a lot of requested features, but the code style, code arrangement and the way package looks now doesn't match my vision. I made my mind only now, because I started working on v4 and I can clearly see, what I want from my code and how the package should look like in the future.

Keep the good work and I hope on your understanding!

**Comment by rankarpan** [comment]
Hi @babenkoivan,
if you need any help for v4, then ask me anytime.

**Comment by babenkoivan** [comment]
Hi @rankarpan, that's very generous of you to offer help. I think will use your offer, but later, when I have some basic stuff done.

**Pull request closed without merging**
