### PR TITLE
enable laravel/scout 8

### PR DESCRIPTION
**Pull request by iamthefreeman**

### CODE REVIEW

**Comment by iamthefreeman** [comment]
@iget-esoares @babenkoivan Any chance this could be looked into?

Thanks,
James.

**Comment by francoism90** [comment]
One review to go. :)

**Comment by shylor** [comment]
It seems like a simple change. Can anyone approve these?

**Comment by shylor** [comment]
Any word on this?

**Comment by Surt** [comment]
Actually I did stop the laravel 7 migration of a system because of this. 

I understand @babenkoivan is busy. I handed over libraries to the community so it could be developed and extended without my continuous supervision. Please @babenkoivan delegate responsabilities so we can help you with this.

**Comment by iget-esoares** [comment]
Sorry for the delay. I'm releasing this as v4.0.4.

**Pull request merged**
